// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Value
    {
        /// <summary>
        /// Initializes a new instance of the Value class.
        /// </summary>
        public Value()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Value class.
        /// </summary>
        public Value(int? equipoId = default(int?), string nombre = default(string))
        {
            EquipoId = equipoId;
            Nombre = nombre;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "equipoId")]
        public int? EquipoId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nombre")]
        public string Nombre { get; set; }

    }
}
