// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace swagger.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Value2
    {
        /// <summary>
        /// Initializes a new instance of the Value2 class.
        /// </summary>
        public Value2()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Value2 class.
        /// </summary>
        public Value2(string nombre = default(string), int? id = default(int?))
        {
            Nombre = nombre;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

    }
}
